### ISSUE TITLE
Provide cluster-wide and namespaced Custom Resources

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#10]
Right now we only have one custom resource which is named `AdmissionPolicy`. This happens to be a cluster-wide resource.

We should come up with two CR: a cluster level and a namespaced one. Moreover, we should expose some of the filtering abilities that Kubernetes' admission webhook server already have.

## Cluster-wide resource

The cluster-wide resource should be called `ClusterAdmissionPolicy`, and look like that:

```yaml
apiVersion: chimera.suse.com/v1alpha1
kind: ClusterAdmissionPolicy
metadata:
  name: privileged-pods
spec:
  module: registry://ghcr.io/chimera-kube/policies/pod-toleration:v0.0.2
  resources:
  - pods
  operations:
  - CREATE
  - UPDATE
  # a 1:1 of https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-matchpolicy
  matchPolicy: Equivalent
  scope: <>? <- 1:1 map with k8s
  # a 1:1 of https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-namespaceselector
  namespaceSelector:
    matchExpressions:
    - key: environment
      operator: In
      values: ["prod","staging"]
  # a 1:1 of https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-objectselector
  objectSelector:
    matchLabels:
      foo: bar
  settings:
    taint_key: dedicated
    taint_value: tenantA
```

By using a cluster-wide policy a user could inspect both cluster-wide and namespaced-based resources.
The `namespaceSelector` and `objectSelector` attributes can help to filter the incoming request and evaluate just a part of them.

## Namespaced CR

We should also offer a CR called `AdmissionPolicy` that is namespaced:

```yaml
apiVersion: chimera.suse.com/v1alpha1
kind: AdmissionPolicy
metadata:
  name: privileged-pods
  namespace: staging
spec:
  module: registry://ghcr.io/chimera-kube/policies/pod-toleration:v0.0.2
  resources:
  - pods
  operations:
  - CREATE
  - UPDATE
  matchPolicy: Exact
  scope: "Namespaced" # hard coded, cannot process cluster-wide resources
  # a 1:1 of https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-objectselector
  objectSelector:
    matchLabels:
      foo: bar
  settings:
    taint_key: dedicated
    taint_value: tenantA
```

Notable differences, compared to the cluster-wide CR:

  * `scope` has always value `Namespaced`
  * There's no `namespaceSelector`

I **think** the `metadata.namespace` value must be passed to the Chimera Policy Server, which will use it to filter incoming requests. It looks like the `namespaceSelector` filter doesn't allow to filter by the name of the namespace, only by its labels.

Note: this includes a rename of the current cluster-wide `AdmissionPolicy` to `ClusterAdmissionPolicy`.
