### ISSUE TITLE
[Epic] Add timeout evaluation configuration in policies CRDs

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#1042]
Recently an user run into [issue](https://github.com/kubewarden/env-variable-secrets-scanner-policy/issues/73) when the audit scanner starts in a environment with  scarce resources. He was running the env-var-secret-scanner policy witch due the dependencies it has to perform secrets scanning it take a little bit longer to run. As the policy server has not that many resources available, all the policy evaluations starts to take longer and eventually, the secret scanner policy hit the policy evaluation timeout. Causing the evaluation to fail. 

To workaround the issue, the user reduced the number of parallel request performed. To be less aggressive in this environment with less computational resources. But this is not ideal. 

The goal of this issue is to consider allowing define evaluation timeout per policy. Therefore, different policies running in the same policy server can have different evaluation timeout. 

### Acceptance criteria
- Decide if this should be implemented
- If decided to add this feature, do it!

**Comment by viccuad** [comment]
### Outcome of the spike

Added sub-issues about implementation details.
As they stand, the UX for policies would be:

- (Cluster)AdmissionPolicies: get `spec.timeoutEvalSeconds`, in addition to the
  already existing `spec.timeoutSeconds` for webhooks.

- (Cluster)AdmissionPolicyGroups: several options,

  - (A). The group gets `spec.timeoutEvalSeconds`. The sub-policies don't get
    any timeoutEvalSeconds.

    This is the POC approach.

    On implementation, this means that the policies' EvaluationEnvironment
    inherits the group timeout value. `spec.timeoutEvalSeconds` is at the same
    level as `spec.TimeoutSeconds` and `spec.failurePolicy`.

  - (B). The sub-policies get a field `timeoutEvalSeconds` each, e.g:

    ```yaml
    apiVersion: policies.kubewarden.io/v1
    kind: ClusterAdmissionPolicyGroup
    metadata:
      name: demo
    spec:
      rules: (...)
      policies:
        signed_by_alice:
          module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.3.0
          timeoutEvalSeconds: 30 # new <--------------------------------------------
          settings:
            modifyImagesWithDigest: false
            signatures:
              - image: "*"
                pubKeys:
                  - |
                    -----BEGIN PUBLIC KEY-----
                    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEyg65hiNHt8FXTamzCn34IE3qMGcV
                    yQz3gPlhoKq3yqa1GIofcgLjUZtcKlUSVAU2/S5gXqyDnsW6466Jx/ZVlg==
                    -----END PUBLIC KEY-----
        reject_latest:
          module: registry://ghcr.io/kubewarden/policies/trusted-repos:v0.2.0
          settings:
            tags:
              reject:
                - latest
      expression: "reject_latest() || (signed_by_alice() && signed_by_bob())"
      message: "the image is using the latest tag or is not signed by Alice and Bob"
    ```

    On implementation, the policies run in parallel each with their own timeout value.

    This makes the UX look closer as the (Cluster)AdmissionPolicies when copy-pasting policies,
    but more different when reasoning about policies in general.

  - (C). Both the group and the policies get a `timeoutEvalSeconds`.

    I discarded this approach as overly complicated, plus one needs to check
    that no policy exceeds the defined timeout at the group level (and then,
    how to apply `spec.failurePolicy`?).

For all cases, the new `timeoutEvalSeconds` honours the existing
`spec.failurePolicy` setting (which defaults to failing closed).
