### ISSUE TITLE
PolicyServer service uses old labels only

### ISSUE THREAD

**Issue by kravciak** [kubewarden/kubewarden-controller#1052]
```yaml
~ k get svc -n cattle-kubewarden-system policy-server-default -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-03-18T12:46:09Z"
  labels:
    app: kubewarden-policy-server-default
  name: policy-server-default
...


~ k get pods -n cattle-kubewarden-system policy-server-default-78b985fdb7-95mcj -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    sidecar.opentelemetry.io/inject: "true"
  creationTimestamp: "2025-03-18T12:54:22Z"
  generateName: policy-server-default-78b985fdb7-
  labels:
    app: kubewarden-policy-server-default
    app.kubernetes.io/component: policy-server
    app.kubernetes.io/instance: policy-server-default
    app.kubernetes.io/managed-by: kubewarden-controller
    app.kubernetes.io/part-of: kubewarden
    kubewarden/config-version: "5351"
    kubewarden/policy-server: default
    pod-template-hash: 78b985fdb7
    sidecar.opentelemetry.io/injected: cattle-kubewarden-system.kubewarden
  name: policy-server-default-78b985fdb7-95mcj
...
```

This causes issues with ServiceMonitor that we use for metrics (empty data).

Blocked PR: https://github.com/rancher/kubewarden-ui/pull/1099
