### ISSUE TITLE
Policy server name label changed to kubewarden.io

### ISSUE THREAD

**Issue by kravciak** [kubewarden/kubewarden-controller#1104]
Policy server label changed from `kubewarden/policy-server=default` to `kubewarden.io/policy-server: default`
It seems like a bug because we still have `kubewarden/config-version`.

```
~ kubectl get pods -n kubewarden policy-server-default-58847c667c-xsbt9 -o yaml | yq '.metadata'
creationTimestamp: "2025-04-17T07:07:31Z"
generateName: policy-server-default-58847c667c-
labels:
  app.kubernetes.io/component: policy-server
  app.kubernetes.io/instance: policy-server-default
  app.kubernetes.io/managed-by: kubewarden-controller
  app.kubernetes.io/part-of: kubewarden
  kubewarden.io/policy-server: default
  kubewarden/config-version: "850"
  pod-template-hash: 58847c667c
...
```

```bash
# 1.23
k get deploy -n kubewarden -o yaml | grep '  kubewarden'
      kubewarden/config-version: "848"
      kubewarden/policy-server: default

# 1.24
~ k get deploy -n kubewarden -o yaml | grep '  kubewarden'
      kubewarden/config-version: "841"
      kubewarden.io/policy-server: default
```

To reproduce install kubewarden with latest images.
Failing e2e test: https://github.com/kubewarden/helm-charts/actions/runs/14502511586/job/40685252439
