### ISSUE TITLE
[policy-server]: Feature Request: strict policies.yml parsing, disallow unknown keys 

### ISSUE THREAD

**Issue by fabriziosestito** [kubewarden/kubewarden-controller#1281]
### Is your feature request related to a problem?

The parsing of `policies.yml` is not strict enough.
This can be prone to errors.

For instance, at the time of writing, this configuration is valid:
```yaml
psp-capabilities:
  url: registry://ghcr.io/kubewarden/policies/psp-capabilities:v0.1.7
  allowedToMutate: true
  policyModel: monitor # note: "policyModel" should be "policyMode" 
  settings:
  ...
```

However, as the `policyMode` key is not found, the policy will be configured in `Protect` mode. 

Also, we could clean up the tests by using fixtures and/or merging tests together in one test with multiple cases of reading configurations.
