### ISSUE TITLE
Can't create ClusterAdmissionPolicies that apply to the same ns as default PolicyServer

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-controller#209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Reported by @Jawery on Slack. 

1. On a fresh cluster, install Kubewarden stack in a different ns (e.g: `jared-ns`).
1. Default policy-server starts fine.
1. Create a clusteradmissionpolicy that targets that ns.
1. A new replicaset is created for policy-server-default. It fails, with `FailedCreate`, and error:
`Error creating: Internal error occurred: failed calling webhook "clusterwide-test-policy.kubewarden.admission": failed to call webhook: the server could not find the requested resource`.
1. kubewarden-controller pod shows no errors here (although at some point, @raulcabello and I did see a controller error, stating that it failed to create the webhook for the policy IIRC).

### Expected Behavior

Correct rollout of PolicyServer deployment, new policy-server pod, serving the policy correctly.

### Steps To Reproduce

Deploy as usual, but with a different kubewarden ns:
```
kubectl create namespace jared-ns

kubectl apply -f https://github.com/jetstack/cert-manager/releases/latest/download/cert-manager.yaml
kubectl wait --for=condition=Available deployment --timeout=2m -n cert-manager --all

helm repo update
helm install --wait -n jared-ns kubewarden-crds kubewarden/kubewarden-crds
helm install --wait -n jared-ns kubewarden-controller kubewarden/kubewarden-controller
helm install --wait -n jared-ns kubewarden-defaults kubewarden/kubewarden-defaults
```

Then, create a simple policy (matching only the same ns in this example):
```
kubectl apply -f - <<EOF
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: test-policy
spec:
  module: registry://ghcr.io/kubewarden/policies/pod-privileged:v0.1.11
  namespaceSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: In
        values:
          - jared-ns
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
  mutating: false
EOF
```

This 

### Environment

```markdown
- OS: Linux
- Architecture: amd64
- Minikube
- kubewarden-controller 0.5.2
```

### Anything else?

This doesn't happen with kubewarden-controller 0.5.0.
