### ISSUE TITLE
Failed policies get incorrect `active` status

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-controller#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Starting a misconfigured policy, that currently makes the policy-server error, still incorrectly marks the policy as `Active`.  

From the `status.conditions.lastTransitionTime`, it also looks to me that the policies start already as `Active` instead of `Scheduled`.

### Expected Behavior

Failing policies should get a different status than `Active`. Particularly, one that corresponds with their state (missing webhooks, or failed to start, etc).

### Steps To Reproduce

1. Deploy Kubewarden as usual
1. Instantiate following misconfigured policy, that has `settings` that fail to validate:
```
kubectl apply -f - <<EOF
---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: volumes-psp
spec:
  policyServer: default
  module: registry://ghcr.io/kubewarden/policies/volumes-psp:v0.1.6
  settings:
    allowedTypes:
      - cannotmixasterisk
      - '*'
  namespaceSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: NotIn
        values:
          - kubewarden
          - kube-system
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
    - UPDATE
  mutating: false
EOF  
``` 
1. policy-server shows:
```
cannot spawn worker error="[registry://ghcr.io/kubewarden/policies/volumes-psp:v0.1.6: settings of policy registry://ghcr.io/kubewarden/policies/volumes-psp:v0.1.6 are invalid: Some(\"Provided settings are not valid\")]"
```
1. Yet, `kubectl get clusteradmissionpolicies` shows the policy as `active`.

### Environment

```markdown
- OS: minikube, linux, docker
- Architecture: amd64
- kubewarden-controller: 0.5.2
```
