### ISSUE TITLE
`ClusterAdmissionPolicy`: handle multiple Rules

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#31]
Right now, `v1alpha1` of `ClusterAdmissionPolicy` allows to set only one matching rule per policy. This is a limitation compared to what a regular Webhook admission controller offers.

# Admission criteria

Change the definition of ClusterAdmissionPolicy to allow multiple [RuleWithOperations](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#rulewithoperations-v1-admissionregistration-k8s-io) objects to be handled by a single policy.

After this change, a ClusterAdmissionPolicy declaration would look like that:

```yaml
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: generated-policy
spec:
  module: "file:///home/flavio/hacking/kubernetes/kubewarden/kwctl/annotated.wasm"
  settings: {}
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - pod
      operations:
        - CREATE
        - UPDATE
  mutating: false
```
