### ISSUE TITLE
Can create `AdmissionPolicy` and `ClusterAdmissionPolicy` with empty `rules`

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Apparently it's possible to create either a `ClusterAdmissionPolicy` or an `AdmissionPolicy` that have empty rules.

This leads the policy in pending state, because it's not possible to create a webhook for it.

### Expected Behavior

Our controller is also exposing an endpoint that is used to validate Kubewarden's CRDs. This validating admission controller should prevent the creation of these kind of broken resources.

### Steps To Reproduce

Create a `ClusterAdmissionPolicy` with the following spec:

```yaml
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: test-bug
spec:
  mode: protect
  module: ghcr.io/kubewarden/policies/disallow-service-nodeport:v0.1.2
  mutating: false
  policyServer: default
  rules:
  - {}
  settings: null
```

The `ClusterAdmissionPolicy` is created, but it stays in `pending` state forever.
