### ISSUE TITLE
New policy: Rancher Manager, block namespace creation if project ResourceQuota exceeds

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#377]
Rancher doesn't block the namespace creation in a project even if the `resourceQuota` allocated to the project is exceeded.
It sets "0" as resources allocated to the newly created namespace which will eventually restrict any pod creation on that specific namespace. However, it would be great to have a validation webhook to block further namespace creation on the project which already have the `resourceQuota` exceeded.

Currently, namespace creation is successful with both rancher UI and kubectl (with project annotation).

## How to reproduce

Create a namespace on the project with a limit value that exceeds the project limit set in the project. Here I have used CPU Reservation(`requestsCpu`) parameter.

Create a project under the Rancher Manager UI:

- Cluster
- Project/Namespaces
- Create Project
- Resource Quota Tab
- Select "CPU Reservation" from the dropdown
- Set Project Limit as 500 and Namespace as Limit as 100
- Create

Get the cluster id(eg: local) combined with Project ID(eg: `p-sd7dh`) and enter in below yaml to create namespace with `requestsCpu` as 400m under the project
 Apply this yaml and its successful:

```yaml


apiVersion: v1
kind: Namespace
metadata:
  name: one
  annotations:
    field.cattle.io/projectId: local:p-sd7dh
    field.cattle.io/resourceQuota: '{"limit":{"requestsCpu":"400m"}}'
  labels:
    field.cattle.io/projectId: p-sd7dh 
```

Create another yaml to create namespace which allocates other available cpus and another namespace which exceeds the cpu reservations for the project:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: two
  annotations:
    field.cattle.io/projectId: local:p-sd7dh
    field.cattle.io/resourceQuota: '{"limit":{"requestsCpu":"100m"}}'
  labels:
    field.cattle.io/projectId: p-sd7dh
---
apiVersion: v1
kind: Namespace
metadata:
  name: three
  annotations:
    field.cattle.io/projectId: local:p-sd7dh
    field.cattle.io/resourceQuota: '{"limit":{"requestsCpu":"100m"}}'
  labels:
    field.cattle.io/projectId: p-sd7dh 
```
Third namespace(three) get created even if its exceed the project limit, though its allocating 0 cpu reservations for that namespace.

In addition to that, create another namespace using Rancher UI >> Cluster >> Project/Namespace >> Create Namespace in the specific project. Even though it's showing "Project Resource Availability" as full, it allows the project creation.

Use below command to check the resource quota allocation

```console
kubectl get resourceQuota -n one -o yaml
kubectl get resourceQuota -n two -o yaml
kubectl get resourceQuota -n three -o yaml
```
 
## Expected behavior
The policy should block the namespace creation with a meaningful message about the quota issue
