### ISSUE TITLE
Policies metadata are incorrect

### ISSUE THREAD

**Issue by kravciak** [kubewarden/kubewarden-controller#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Policy resources specified by singular word, for example `pod` or `deployment` are not recognized and blocked. Valid resources name is plural - `pods`, `deployments` .

```
~ kwctl pull ghcr.io/kubewarden/policies/pod-privileged:v0.2.3
~ kwctl scaffold manifest --type=ClusterAdmissionPolicy registry://ghcr.io/kubewarden/policies/pod-privileged:v0.2.3
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: pod-privileged
spec:
  module: registry://ghcr.io/kubewarden/policies/pod-privileged:v0.2.3
  settings: {}
  rules:
  - apiGroups:
    - ''
    apiVersions:
    - v1
    resources:
    - deployment
    - replicaset
    - statefulset
    - daemonset
    - replicationcontroller
    - job
    - cronjob
    - pod
    operations:
    - CREATE
```

Briefly checking for singular resources in our policies shows more of them are affected: 
```
https://github.com/kubewarden/env-variable-secrets-scanner-policy/blob/main/artifacthub-pkg.yml
https://github.com/kubewarden/volumeMounts-policy/blob/main/artifacthub-pkg.yml
https://github.com/kubewarden/environment-variable-policy/blob/main/artifacthub-pkg.yml
https://github.com/kubewarden/user-group-psp-policy/blob/main/artifacthub-pkg.yml
https://github.com/kubewarden/allow-privilege-escalation-psp-policy/blob/main/artifacthub-pkg.yml
```

# Policies to check

These are the policies we have to check, to ensure they have correct metadata:

- [x] allow-privilege-escalation-psp-policy
- [x] allowed-fsgroups-psp-policy
- [x] allowed-proc-mount-types-psp-policy
- [x] apparmor-psp-policy
- [x] capabilities-psp-policy
- [x] deprecated-api-versions-policy
- [x] disallow-service-loadbalancer-policy
- [x] disallow-service-nodeport-policy
- [x] echo-policy
- [x] env-variable-secrets-scanner-policy
- [x] environment-variable-policy
- [x] flexvolume-drivers-psp-policy
- [x] host-namespaces-psp-policy
- [x] hostpaths-psp-policy
- [x] ingress-policy
- [x] pod-privileged-policy
- [x] pod-runtime-class-policy
- [x] readonly-root-filesystem-psp-policy
- [x] safe-annotations-policy
- [x] safe-labels-policy
- [x] seccomp-psp-policy
- [x] selinux-psp-policy
- [x] sleeping-policy
- [x] sysctl-psp-policy
- [x] trusted-repos-policy
- [x] user-group-psp-policy
- [x] verify-image-signatures-policy
- [x] volumeMounts-policy
- [x] volumes-psp-policy
