### ISSUE TITLE
Feature Request: validate rules API groups.

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#397]
### Is your feature request related to a problem?

There is nothing in the controller preventing users from configuring policy rules with invalid API groups. Causing admission request to be ignored by the policy.

### Solution you'd like

The controller should validate the policy rules. It should validates if the resource names are valid and if they belongs to the API group which is defined in the policy definition. 

For example, the user should not be able to define a policy as the following:

```yaml
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: pod-privileged
spec:
  module: registry://ghcr.io/kubewarden/policies/pod-privileged:v0.2.3
  settings: {}
  rules:
  - apiGroups:
    - ''
    apiVersions:
    - v1
    resources:
    - deployment
    - pod
    operations:
    - CREATE
```

The resources should be in the plural (e.g. `deployments` and `pods`). Furthermore, there is no `deployment` (or `deployments`) in the `core` API groups (here defined by the  `''` string). Therefore, the controller should allow the policy only if it has a dedicated rule for the `apps` API group resources, like `deployments`.   

### Anything else?

Maybe the controller can use the API used by the command `kubectl api-resources` to check which API group a resource belongs to.
