### ISSUE TITLE
Add `contextAware` field to `ClusterAdmissionPolicy`

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#400]
As described in the [context-aware policies RFC](https://github.com/kubewarden/rfc/blob/main/rfc/0015-context-aware-policies.md), the `ClusterAdmissionPolicy` resource has to be extended to have a new attribute:

```yaml
contextAware:
# - apiVersion: <apiVersion>
#   kind: <kind>
- apiVersion: v1
  kind: Pod
- apiVersion: apps/v1
  kind: Deployment
- apiVersion: networking.k8s.io/v1
  Kind: Ingress
```

The name of the attribute is `contextAware` and it points to a list of objects. Each object has the following structure:

* `apiVersion`: has a string as value
* `kind`: has a string as value
