### ISSUE TITLE
Policy Server configuration: take `contextAwareResources` field into consideration

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#401]
> **Note:** this issue depends on https://github.com/kubewarden/kubewarden-controller/issues/400

When generating the `policies.yml` file of a Policy Server instance, the controller has to take into account the freshly added `contextAwareResources` attribute.

The configuration snippet for a `ClusterAdmissionPolicy` that has `contextAwareResources` details, will look like that:

```yaml
namespace-validate:
  url: file:///tmp/namespace-validate-policy.wasm
  allowedToMutate: false
  contextAwareResources:
  - apiVersion: v1
    kind: Pod
  - apiVersion: apps/v1
    kind: Deployment
  - apiVersion: networking.k8s.io/v1
    Kind: Ingress
  settings:
    valid_namespace: valid
```

There's a new `contextAwareResources` attribute that is basically a dump of the `contextAwareResources` field of the `ClusterAdmissionPolicy` Custom Resource
