### ISSUE TITLE
Allow to inject custom certificate authorities

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/kubewarden-controller#41]
Some users might want to pull policies from https/OCI registries that are secured using self-signed certificates.

This can be done by starting the Policy Server process with a specially crafted `sources.yml` file.
The format of the file is described [here](https://github.com/kubewarden/policy-server/wiki/Configuration#sources-path---sources-path).

To address this issue, we will have to produce a `sources.yml` file that looks like that:

```yaml
source_authorities:
  "internal-registry.dev.my-company.com": /local/path/to/internal-registry-dev-mycompany-com.pki
  "other-internal-registry.dev.my-company.com:5001": /local/path/to/other-internal-registry-dev-mycompany-com.pki
```

## Design

We will extend the Policy Server CRD to have a new attribute named `sourceAuthorities`. This attribute is a map with:
  * key (string): the name of the registrie (e.g.: "internal-registry.dev.my-company.com")
  * value (string): the PEM encoded certificate authority that has to be used to verify the certificate used by the endpoint

The user can change at any time the value of the `sourceAuthorities` attribute, this will lead to a rollout of the PolicyServer Deployment.

Behind the scenes, the controller will update a ConfigMap that has a key named `sources.yml`, with a string as value. The string will hold the contents of the `sources.yml` file.
The ConfigMap will also have one entry per certificate specified with:
  * key (string): the name of the file that has to be generated
  * value (string): the actual certificate

This ConfigMap is then mounted into the Policy Server Pods. The Policy Server Pod Template is updated to make use of this `sources.yml` file.

We can probably extend the already existing ConfigMap that each Policy Server already uses to store the contents of the `policies.yml` file.

Given the following `sourceAuthorities`:

```yaml
source_authorities:
  "internal-registry.dev.my-company.com": <pem cert1>
  "other-internal-registry.dev.my-company.com:5001": <pem cert2>
```

The ConfigMap created by the controller will be the following one:

```yaml
sources.yaml: |
  source_authorities:
    "internal-registry.dev.my-company.com": internal-registry.dev.my-company.com.pem
    "other-internal-registry.dev.my-company.com:5001": other-internal-registry.dev.my-company.com:5001.pem
internal-registry.dev.my-company.com.pem: <pem cert1>
other-internal-registry.dev.my-company.com:5001.pem: <pem cert2>
```

## Acceptance criteria

* The PolicyServer Custom Resource is extended to have an attribute named `sourceAuthorities`
* By default the map has no entries
* User can add custom CAs by populating the `sourceAuthorities` attribute
* Custom CAs can be added/remove at any time. Any change done to this attribute leads to the rollout of the PolicyServer Deployment

**Comment by flavio** [comment]
Waiting for the new architecture to be in place

**Comment by viccuad** [comment]
@kubewarden/kubewarden-developers the more I go with it, the less I like it. I would like to change policy-server as explained in option 3 below.

I have an implementation: see https://github.com/viccuad/kubewarden-controller/commit/680433b8b8f104f67634ba1f8ef793f6a18e406b.

That implementation currently leaks entries in sha512 in the configmap. See the FIXME
https://github.com/viccuad/kubewarden-controller/commit/680433b8b8f104f67634ba1f8ef793f6a18e406b#diff-27a2d1900a29003599483bb04572874f55b0198334d916d5c26e566bc63d8cf1R92-R111

On an update to the PolicyServer confimap, we have:
```yaml
data:
  b0e018a10878ee63f1dad41be8a972d3c1b23a0109b7ef671589acda0abed0d5: pem cert 1
  fe7faa899a162befbe70285b92a2ee5a57dac329720f2adfde184b4e267ac2bc: pem cert 2
  policies.yml: '{}'
  sources.yml: '{"source_authorities":{"host.k3d.internal:5000":"/sources/b0e018a10878ee63f1dad41be8a972d3c1b23a0109b7ef671589acda0abed0d5","host.k3d.internal:999":"/sources/fe7faa899a162befbe70285b92a2ee5a57dac329720f2adfde184b4e267ac2bc"}}'
kind: ConfigMap 
```
Those sha512 entries cannot be easily removed on reconciling an update. Options that I see:

1. Prepend sha512 with `cert-`, iterate through Data map, delete()
    keys that start with `cert-`. Eek.
2. Instead of doing Client.Patch(cfg), do Client.Delete(cfg) &&
    Client.Create(cfg). Also eek.
3. Change behaviour of policy-server, from expecting paths to certs
  in `sources.yaml`, to accept certs there. With that, we don't need the
  sha512 entries in Data, nor mounting them as files.
