### ISSUE TITLE
Default policy server does not create metrics port on edit

### ISSUE THREAD

**Issue by kravciak** [kubewarden/kubewarden-controller#432]
When I edit existing default policyServer and enable telemetry it should create metrics port.
This does not happen, metrics port is created only when I enable telemetry during initial chart installation.

All grafana fields are then filled with zeroes because of this.

### Current behavior
Enabling telemetry on existing policyServer does not create metrics port:
```yaml
# Clusters -> local -> Instaled Apps -> rancher-kubewarden-defaults -> Edit
policyServer:
  telemetry:
    enabled: false -> true

# kubectl get svc -n cattle-kubewarden-system policy-server-default -o yaml | yq -r '.spec.ports'
- name: policy-server
  port: 8443
  protocol: TCP
  targetPort: 8443
```

### What works (workaround)
- delete existing policy server (Instaled Apps -> rancher-kubewarden-defaults -> delete)
- create default policy server again, enable telemetry `DURING` installation

```yaml
# kubectl get svc -n cattle-kubewarden-system policy-server-default -o yaml | yq -r '.spec.ports'
- name: policy-server
  port: 8443
  protocol: TCP
  targetPort: 8443
- name: metrics
  port: 8080
  protocol: TCP
  targetPort: 8080
```

### Steps to reproduce:
- install opentelemetry
- install kubewarden + default policyserver from Rancher UI
- install monitoring from `Rancher UI -> Cluster tools` (change `prometheus -> additionalServiceMonitors` as described [here](https://docs.kubewarden.io/operator-manual/ui-extension/metrics#1-within-the-cluster-explorer-click-on-cluster-tools-in-the-side-navigation), use `cattle-kubewarden-namespace`
- edit rancher-kubewarden-controller app, set `telemetry: enabled: false -> true`
- edit rancher-kubewarden-defaults app, set `policyServer: telemetry: enabled: false -> true`
