### ISSUE TITLE
New policy: PSA label enforcer

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#451]
Create a mutating policy that ensure [PSA labels](https://kubernetes.io/docs/concepts/security/pod-security-admission/) are always set on Namespace objects.

The policy would enforce the PSA modes provided by the user to be always set. This prevents users from changing the PSA profile to a lower value.

The policy would take a configuration like that:

```yaml
# Mode label that are enforced.
#
# Level label values must be one of:
# - "privileged"
# - "baseline"
# - "restricted"
#
# Version (optional) label values must be one of:
# - "latest"
# - specific version like "v1.27"
modes:
  enforce: "privileged"
  enforce-version: "latest"
  audit: "privileged"
  audit-version: "latest"
  warn: "privileged"
  warn-version: "latest"   
```

> Note: this is deliberately resembles the configuration format of the [PSA admission controller](https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/#configure-the-admission-controller)

## Policy behavior

The policy ensures the `modes` specified by the user are always set. The policy will handle only the modes that have been defined. For example, given the following configuration:

```yaml
modes:
  enforce: "baseline"
  enforce-version: "latest"
```

The Namespace will have these labels set:
* `pod-security.kubernetes.io/enforce: baseline`
* `pod-security.kubernetes.io/enforce-version: latest`

Other PSA related labels that might be specified by the Namespace object are going to be left unchanged.

## Settings validation

Settings must be validated to ensure the following rules are respected:

* keys can be only: `enforce`, `enforce-version`, `audit`, `audit-version`, `warn` and `warn-version`
* values or the `enforce`, `audit` and `warn` keys must be one of `privileged`, `baseline`, or `restricted`
* values of the `<MODE>-version` can be either `latest` or a minor version `v<Major>.<Minor>` (like `v1.27`)
* specifying a `<MODE>-version` attribute, but not `<MODE>` should cause a validation failure

**Comment by flavio** [comment]
> Thanks a lot for this feature! Just to be sure to be sure - does this allow a configuration via Kubewarden like:
> 
>     1. all existing and all new namespaces should automatically get enforce: "restricted"" and

Only the new ones or the already existing ones that for whatever reason are updated after the policy is enforced
 
>     2. the namespaces existing or newly created with the names "kube-system, cattle-monitoring-system" should automatically get "enforce: "priviledged""

The policy right now doesn't distinguish between the Namespace names. You would have to deploy this policy as a `ClusterAdmissionPolicy`, configure it to enforce `privileged` and then use a label selector to enforce it. The "privileged" namespaces must be discoverable by this label.

Something like that:

```yaml
---
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: psa-enforcer-privileged-namespaces
spec:
  module: registry://ghcr.io/kubewarden/policies/psa-label-enforcer:v0.1.1
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["namespaces"]
    operations:
    - CREATE
    - UPDATE
  mutating: true
  namespaceSelector:
     matchExpressions:
     - key: "kubernetes.io/metadata.name"
       operator: In
       values: [kube-system, cattle-monitoring-system]
  settings:
    modes:
      enforce: "privileged"
---
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: psa-enforcer-default-mode
spec:
  module: registry://ghcr.io/kubewarden/policies/psa-label-enforcer:v0.1.1
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["namespaces"]
    operations:
    - CREATE
    - UPDATE
  mutating: true
  namespaceSelector:
     matchExpressions:
     - key: "kubernetes.io/metadata.name"
       operator: NotIn
       values: [kube-system, cattle-monitoring-system]
  settings:
    modes:
      enforce: "restricted"
```
