### ISSUE TITLE
Create a `PolicyServer` custom resource

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/kubewarden-controller#47]
The `PolicyServer` custom resource will resemble a policy server deployment. It supports several configuration settings. An example follows:

```yaml
apiVersion: policies.kubewarden.io/v1alpha2
kind: PolicyServer
metadata:
  name: reserved-instance-for-tenant-a
spec:
  image: ghcr.io/kubewarden/policy-server:v1.0.0
  replicaSize: 2
  env:
  - name: KUBEWARDEN_LOG_LEVEL
    value: debug
  - name: KUBEWARDEN_LOG_FMT
    value: jaeger
  annotations:
    sidecar.jaegertracing.io/inject: default
```

The initial custom resource is going to have the following attributes:

- `image`
- `replicaSize`
- `env`
- `annotations`
- `serviceAccountName`: if nothing is provided, the created deployment does not specify any service account, that will make Kubernetes default it to the namespace default.

All these attributes will be forwarded to the deployment being reconciled. In the future, other attributes could be added, such as `sources`, but we will leave that for a later time.

**Acceptance criteria**

- A new CRD called `PolicyServer` is created with the attributes mentioned before. The custom resource is cluster-wide.
- It is fine for `kubebuilder` to generate an empty controller, but this card does not cover any implementation of the controller itself.
