### ISSUE TITLE
Feature Request: generic optional field in ValidationRequest 

### ISSUE THREAD

**Issue by RealHarshThakur** [kubewarden/kubewarden-controller#512]
### Is your feature request related to a problem?

I'd like Kubewarden to be a generic policy evaluation engine like OPA is, to have all the rich developer experience of kubewarden and still be able to deploy it without being tied to K8s paradigms. Few reasons:
 
* Allows for Policy server to be deployed and be useful outside K8s environments. This can allow people to migrate off of OPA, if they want to and widen their policy definition languages
* Policies can be evaluated against things that aren’t deployment artifacts( maybe static analysis, test coverage, etc)
* Preserves the developer experience of writing policies with low learning curve.

### Solution you'd like

I think policy-server should accept an optional field in ValidationRequest to remain backward compatible.  Policy evaluation can then use this field over AdmissionRequest.  

### Anything else?

Slack discussion: https://kubernetes.slack.com/archives/C01T3GTC3L7/p1693532273095639

**Comment by flavio** [comment]
Thanks for having opened this feature request. The possibility to use Kubewarden to evaluate non-kubernetes data has been evaluated in the past, but we preferred to focus on a specific use case (kubernetes admission controller) as a starting point.

It would be possible to extend Policy Server to allow the evaluation of custom JSON documents. I would envision something like that.

## Policy Server settings

We could extend the [`policies.yml`](https://github.com/kubewarden/policy-server/blob/main/policies.yml.example) to allow add a new `evaluation_mode` attribute to each policy. By default this attribute would be `kubernetes`, but another allowed value would be `raw`.

For example:

```yaml
psp-apparmor:
  url: registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.7
  evaluation_mode: kubernetes
psp-capabilities:
  url: registry://ghcr.io/kubewarden/policies/psp-capabilities:v0.1.7
  # no `evaluation_mode`, by default use `kubernetes`
  settings:
    allowed_capabilities: ["*"]
    required_drop_capabilities: ["KILL"]
code-license:
  url: registry://ghcr.io/flavio/policies/sbom-license:v0.0.1
  evaluation_mode: raw
  settings:
    allow: ["AGPL-3.0-only", "MIT"]
    deny = ["GPL-2.0-only", "GPL-2.0-or-later", "MPL-2.0"]
```

## Policy Server REST API

All the policies would still be available under the `POST /validate/<policy-id>` route. The endpoint already takes a JSON document as body of the request.

Right now the Policy Server code attempts to convert the JSON document into a Kubernetes AdmissionRequest object. We could change the code to behave differently, according to the `evaluation_mode` specified inside of the configuration file.

The current code would still be used when the `evaluation_mode` is set to `kubernetes`. Attempting to evaluate something that doesn't fit the description of a AdmissionRequest object would return a HTTP 400 Bad Request response.

However, when the `evaluation_mode` is set to `raw`, the code would simply ensure the uploaded data is a valid JSON document.

## Policy Evaluation

Right now all our policies expose two waPC functions. These functions take as input a stream of bytes and return another stream of bytes as response. These stream of bytes must contain a valid JSON document. 

Right now all our SDKs provide high level libraries that try to convert input stream of bytes into a [`ValidationRequest`](https://docs.kubewarden.io/writing-policies/spec/validating-policies#the-validationrequest-object). However, nobody forces the policy author to use our high level SDK. That means the policy can decode the input byte stream into an object like:

```hcl
{
   "request": {
      // whatever JSON object was given via the POST request
   }, 
   "settings": {
     // the usual settings of the policy, as specified by the user via policies.yml
   }
}
```

The policy must still return a [`ValidationResponse`](https://docs.kubewarden.io/writing-policies/spec/validating-policies#the-validationresponse-object) object.

We could later expand the SDKs to provide higher level APIs to deal with this use case.

This is a rough idea, what do you think about that?
