### ISSUE TITLE
Audit scanner does not update timestamps

### ISSUE THREAD

**Issue by kravciak** [kubewarden/kubewarden-controller#517]
Resource age shows time of the first audit scanner check (when it was created).
I suggests resource is not recent, it should show time of last update instead.

### To reproduce:
I changed audit scanner cronjob to run every minute, then display reports.
Even if there is change in results timestamp stays the same.
```bash
ε k get cronjobs.batch -n kubewarden                                                                                                                                                                                                    0.104s
NAME            SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
audit-scanner   */1 * * * *   False     0        34s             15m

ε k get policyreports.wgpolicyk8s.io -A                                                                                                                                                                                                 0.079s
NAMESPACE   NAME            PASS   FAIL   WARN   ERROR   SKIP   AGE
thens       polr-ns-thens   6      0      0      0       0      4m42s

ε k get clusterpolicyreports.wgpolicyk8s.io                                                                                                                                                                                             0.090s
NAME               PASS   FAIL   WARN   ERROR   SKIP   AGE
polr-clusterwide   0      0      0      0       0      8m

# Create resource that fails does not update timestamp
ε k get policyreports.wgpolicyk8s.io -A                                                                                                                                                                                                 0.088s
NAMESPACE   NAME            PASS   FAIL   WARN   ERROR   SKIP   AGE
thens       polr-ns-thens   11     1      0      0       0      11m
```

**Comment by flavio** [comment]
I suspect this is fine, because the `AGE` is about the creation time. I assume (please @viccuad / @jvanz  correct me if I'm wrong) we keep updating the contents of the PolicyReport objects, hence it's expected to not have this field changed.

**Comment by viccuad** [comment]
The `AGE` is indeed about creation time.
The (Cluster)PolicyReports have `metadata.managedFields[]apiVersion.time` and `metadata.resourceVersion` that tells us if it was updated. The contents `PolicyReportResults` don't have any.

E.g, doing a describe:

```yaml
Name:         polr-ns-default
Namespace:    default
Labels:       app.kubernetes.io/managed-by=kubewarden
Annotations:  <none>
API Version:  wgpolicyk8s.io/v1beta1
Kind:         PolicyReport
Metadata:
  Creation Timestamp:  2023-09-07T13:54:07Z
  Generation:          14
  Managed Fields:
    API Version:  wgpolicyk8s.io/v1alpha2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:app.kubernetes.io/managed-by:
      f:results:
      f:scope:
        .:
        f:name:
        f:resourceVersion:
        f:uid:
      f:summary:
        .:
        f:error:
        f:fail:
        f:pass:
        f:skip:
        f:warn:
    Manager:         audit-scanner
    Operation:       Update
    Time:            2023-09-08T08:53:50Z                <----
  Resource Version:  19146                                  <----
  UID:               aba18ff3-19af-4927-8c20-c215f4745455
```

Closing, as this is expected behaviour.
