### ISSUE TITLE
Understand how gatekeeper expects context aware to be formulated

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#538]
Gatekeeper can provide information about cluster resources to all its policies during their evaluation. The information shared with the policies is specified via the ['replicating data' feature](https://open-policy-agent.github.io/gatekeeper/website/docs/sync/) of gatekeeper.

All this data is then added to the incoming JSON object being evaluated by Rego. We have to understand the structure of the JSON object. There's already an explanation inside of the "replicating data" link shared above, however we could also do some debugging of the incoming data by using [this "trick"](https://open-policy-agent.github.io/gatekeeper/website/docs/debug/).

Admission criteria:

* Understand how to expand the incoming JSON object to include also data about the cluster

**Comment by viccuad** [comment]
Returned the card to the TODO list and unassigned, didn't get any meaningful progress so far. I can re-grab it later on :).

**Comment by flavio** [comment]
If you don't care about the process, jump straight to the section about the inventory.

## Testing environment

I've deployed gatekeeper using their helm chart, then I defined this configuration:

```yaml
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "gatekeeper-system"
spec:
  sync:
    syncOnly:
      - group: ""
        version: "v1"
        kind: "Namespace"
      - group: ""
        version: "v1"
        kind: "Pod"
```

Just to be sure, I restarted the gateway-controller-manger deployment.

I then defined this template:

```yaml
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sdenyall
spec:
  crd:
    spec:
      names:
        kind: K8sDenyAll
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdenyall

        violation[{"msg": msg}] {
          msg := sprintf("%s", [data.inventory])
        }
```

and then this constraint that makes use of it:

```yaml
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDenyAll
metadata:
  name: deny-all-namespaces
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
```

Finally I triggered a rejection via:

```console
kubectl create ns foo
```

The output is going quite long, it can be saved to a file in this way:

```console
kubectl create ns foo 2&> output
```

It can then be edited to remove the initial message coming from the kubernetes API server, so that only the JSON data can be left into the file.

Note: it looks like Rego's `sprintf` is having issues with the size of the JSON object. The object is truncated/repeated... there's definitely some memory corruption going on.
It's possible to narrow down the results of the violation by updating the template, for example:

```rego
package k8sdenyall

violation[{"msg": msg}] {
  msg := sprintf("%s", [data.inventory["namespace"]["gatekeeper-system"]])
}
```

This will print only the Pods defined under the `gatekeeper-system` namespace.

## The `inventory` object

As documented [here](https://open-policy-agent.github.io/gatekeeper/website/docs/sync/), the Kubernetes details are made available to all the policies via the `data.inventory` object.

Inventory is a JSON dictionary built using the rules mentioned by the doc:
 - For cluster-scoped objects: `data.inventory.cluster[<groupVersion>][<kind>][<name>]`
-  For namespace-scoped objects: `data.inventory.namespace[<namespace>][groupVersion][<kind>][<name>]`

For example, all the `Namespace` objects are exposed this way:

```hcl
  "cluster": { # that's because Namespace is a cluster wide resournce
    "v1": { # this is the group version of the `Namespace` resource
      "Namespace": { # this is the kind used by `Namespace`
           "default": { # this is the name of the Namespace resource being "dumped"
               # contents of `kubectl get ns default -o json`
           },
           "kube-system": { # name of the namespace
              # contents of the namespace object
           }
           # more entries...
       }
    }
  }
```

While all the Pods are exposed in this way:

```hcl
  "namespace": { # this is used for namespaced resources, like `cluster` was used before for cluster-wide ones
    "gatekeeper-system": { # name of the namespace that contains the Pod
      "v1": { # the group version of the Pod resource
        "Pod": { # the kind of the Pod resource
          "gatekeeper-audit-fd9c6d89d-lrr9d": { # the name of the Pod
               # contents of `kubectl get pod -n gatekeeper-system -o json gatekeeper-audit-fd9c6d89d-lrr9d`
          }
          # the other pods defined inside of the `gatekeeper-system` namespace are shown here
        }
      },
      "default": { # all the pods defined under the `default` namespace
         "v1": {
           "Pod": {
              "foo": {
                 # definition of the `foo` pod, defined under the `default` namespace
              }
           }
        }
      }
   }
```
