### ISSUE TITLE
New policy: `emptyDir` volume size constraint

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#594]
# Description

Requires that any `emptyDir` volumes specify a `sizeLimit`.

Optionally, a `maxSizeLimit` parameter can be supplied in the constraint to specify a maximum allowable size limit.
Optionally, a `defaultSizeLimit` parameter can be supplied to specify the default value to add to a `emptyDir` definition when it doesn't have any value specified.

## Configuration

The policy will have the following configuration format:

```yaml
# optional - the maximum size a user can request
maxSizeLimit: "1G"

# optional - the value to be used when the user didn't specify anything
defaultSizeLimit: "200M"
```

# Possible scenarios

This table summarizes all the possible scenarios for this policy:

| `maxSizeLimit` | `defaultSizeLimit` | Outcome                                                                                                                                                                 |
|--------------|------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 100M         | -                | Creation rejected if the size is missing or if it's more than 100M                                                                                                      |
| -            | -                | Creation rejected if the size is missing. Any value provided by the user is accepted                                                                                    |
| -            | 100M             | Any value provided by the user is accepted. If no value is provided, the policy mutates the resource and changes the emptyDir to have a maximum size of 100M            |
| 100M         | 50M              | Creation is rejected is the requested size is > 100M; otherwise the value provided by the user is accepted. If no value is provided, the policy will set a limit of 50M |
| 100M         | 200M             | Configuration validation failure: the default size limit cannot be more than the maximum allowed size                                                                   |

# Notes

This is going to be a mutating policy

**Comment by flavio** [comment]
@Martin-Weiss, @raif-ahmed can you check the description of the policy to ensure it matches your requirements? I've added the mutation bits to the policy requirements, I think it would be nice to have it. If you don't like it we can drop it

**Comment by raif-ahmed** [comment]
@flavio emptyDir cannot support maxSizeLimit as per K8s docs [only attribute is **sizeLimit**](https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/volume/#local-temporary-directory) 

example 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: registry.k8s.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi
  ```
