### ISSUE TITLE
New policy: Disallow Duplicate Deployment ServiceAccount

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#595]
# Description

Policy to check if every Deployment is using a unique service account, and rejects if the deployment's service account is already in use by a existing deployment. 

# Examples

Given the following Deployment is already defined:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

The creation of the following Deployment is going to be accepted:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: default
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      serviceAccountName: wordpress
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
```

The creation is allowed because the `serviceAccountName` is different.

The creation of the following Deployment is **not** going to be allowed:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: default
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      serviceAccountName: nginx
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
```

The creation is rejected because the `nginx` service account is already in use by the `nginx-deployment` resource.

The creation of the following Deployment is going to be accepted:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: internal
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      serviceAccountName: nginx
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
```

The creation is allowed despite the workload using the `nginx` service account. That happens because this deployment is done inside of a different Namespace (`staging` vs `default`).

# Notes

This is going to be a context aware policy that requires access to the `Deployment` resources
