### ISSUE TITLE
New policy: validate `PersistentVolumeClaim` storage class 

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#688]
The goal of this policy is to prevent the usage of certain storage classes inside of `PersistentVolumeClaim` objects.

Optionally, the policy can be configured to mutate the `PersistentVolumeClaim` to use a fallback storage class when a denied storage class is requested.

When the PersistentVolumeClaim does not have a `storageClassName` set, Kubernetes can fall back to use the default storage class of the cluster. This is something the policy is not intended to check right now.

## Configuration

The policy takes the following parameters:

```yaml
# the list of storage classes that cannot be used
deniedStorageClasses:
- fast
- nvme

# optional - the storage class to be used when a denied is requested
fallbackStorageClass: slow
```

## Examples

Given the following configuration:

```yaml
deniedStorageClasses:
- fast
```

The following `PersistentVolumeClaim` would be accepted:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
```

While the following `PersistentVolumeClaim` would be rejected:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
```

### Mutation

Given the following configuration

```
deniedStorageClasses:
- fast

fallbackStorageClass: cheap
```

Given the following `PersistentVolumeClaim` definition:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
```

The request would be accepted, but the `PersistentVolumeClaim` would be mutated to be:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: cheap
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
```
