### ISSUE TITLE
PolicyGroups CRDs do not match PolicyServer config

### ISSUE THREAD

**Issue by fabriziosestito** [kubewarden/kubewarden-controller#872]
### Is your feature request related to a problem?

PolicyGroups CRDs do not match the PolicyServer config.
Policy group members are expressed as an array in the CRD/RFC, while PolicyServer uses a map.

E.g.

PolicyServer config:
```yaml
pod-image-signatures: # policy group
  policies:
    sigstore_pgp:
      url: ghcr.io/kubewarden/policies/verify-image-signatures:v0.2.8
      settings:
        signatures:
          - image: "*"
            pubKeys:
              - "-----BEGIN PUBLIC KEY-----xxxxx-----END PUBLIC KEY-----"
              - "-----BEGIN PUBLIC KEY-----xxxxx-----END PUBLIC KEY-----"
    sigstore_gh_action:
      url: ghcr.io/kubewarden/policies/verify-image-signatures:v0.2.8
      settings:
        signatures:
          - image: "*"
            githubActions:
            owner: "kubewarden"
    reject_latest_tag:
      url: ghcr.io/kubewarden/policies/trusted-repos-policy:v0.1.12
      settings:
        tags:
          reject:
            - latest
  expression: "sigstore_pgp() || (sigstore_gh_action() && reject_latest_tag())"
  message: "The group policy is rejected."
  ```
  
CRD:
```yaml
  policies:
   - name: sigstore_pgp
     url: ghcr.io/kubewarden/policies/verify-image-signatures:v0.2.8
     settings:
      signatures:
        - image: "*"
          pubKeys:
            - "-----BEGIN PUBLIC KEY-----xxxxx-----END PUBLIC KEY-----"
            - "-----BEGIN PUBLIC KEY-----xxxxx-----END PUBLIC KEY-----"
    - name: sigstore_gh_action:
      url: ghcr.io/kubewarden/policies/verify-image-signatures:v0.2.8
      settings:
        signatures:
          - image: "*"
            githubActions:
            owner: "kubewarden"
....
  ```

### Solution you'd like

- [x] update the CRD to use a map instead of an array in the policy group members field: https://github.com/kubewarden/kubewarden-controller/pull/878
- [x] update the helm chart
- [x] update the RFC accordingly
