### ISSUE TITLE
Weird `settings` section when describing a ClusterAdmissionPolicy

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#88]
I've defined a CluserAdmissionPolicy using this definition:

```yaml
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: safe-labels
spec:
  module: registry://ghcr.io/kubewarden/policies/safe-labels:v0.1.5
  settings:
    constrained_labels:
      owner: ".*" # <- this label is mandatory
  rules:
    - apiGroups:
        - "*"
      apiVersions:
        - "*"
      resources:
        - "*"
      operations:
        - CREATE
        - UPDATE
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values: ["default"]
  mutating: false
```

The output produced by `kubectl get clusteradmissionpolicies.policies.kubewarden.io safe-labels -o yaml` provides what I would expect:

```console
# trimming useless stuff
spec:
  module: registry://ghcr.io/kubewarden/policies/safe-labels:v0.1.5
  mutating: false
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - default
  policyServer: default
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - '*'
  settings:
    constrained_labels:
      owner: .*
```

As you can see the settings section is exactly what I defined inside of the original yaml file.

However, the describe command gives a wrong output:

```console
$ kubectl describe clusteradmissionpolicies.policies.kubewarden.io safe-labels
Name:         safe-labels
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  policies.kubewarden.io/v1alpha2
Kind:         ClusterAdmissionPolicy
Metadata:
# leaving out useless stuff
Spec:
  Module:    registry://ghcr.io/kubewarden/policies/safe-labels:v0.1.5
  Mutating:  false
  Namespace Selector:
    Match Expressions:
      Key:       kubernetes.io/metadata.name
      Operator:  In
      Values:
        default
  Policy Server:  default
  Rules:
    API Groups:
      *
    API Versions:
      *
    Operations:
      CREATE
      UPDATE
    Resources:
      *
  Settings:
    constrained_labels:
      Owner:  .*
```

Now it looks like the `constrained_labels` value is `Owner` (with uppercase `o`).

I don't know if that's even our fault, I just got confused by it while debugging a policy
