### ISSUE TITLE
Regarding Namespace owner label policy using kubewarden

### ISSUE THREAD

**Issue by saiben10** [kubewarden/kubewarden-controller#912]
Hello,

I want the user to restrict the namespace creation if he doesn't provide the namespace owner label. The below is the code. Even though i applied this status is showing pending and able to create a namespace without owner label.But when default policies are working fine.
What i need to make change to fix it.

```yaml
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: psa-enforcer-privileged-namespaces
spec:
  module: registry://ghcr.io/kubewarden/policies/psa-label-enforcer:v0.1.1
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["namespaces"]
      operations:
        - CREATE
        - UPDATE
  mutating: true
  namespaceSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: In
        values: [kube-system]
  settings:
    required_labels:
      - owner
```

**Comment by flavio** [comment]
I've moved the issue to the controller repository and I've added the syntax highlighting to the original message

**Comment by flavio** [comment]
> I want the user to restrict the namespace creation if he doesn't provide the namespace owner label.

You want to enforce all namespaces to have a label `owner` set. Do I get it right?

If that's what you're looking for, you have to use [this policy](https://artifacthub.io/packages/kubewarden/safe-labels/safe-labels), not the one that is defined inside of the policy definition you provided.
Also, the settings you provided for the PSA Label enforcer are wrong, they are not part of the policy (see [here](https://artifacthub.io/packages/kubewarden/psa-label-enforcer/psa-label-enforcer)). That's why the policy stays in status pending, because the validation of the settings fails.

You should define a policy like this one:

```yaml
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: namespace-must-have-owner-label
spec:
  module: ghcr.io/kubewarden/policies/safe-labels:v0.1.14
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["namespaces"]
      operations:
        - CREATE
        - UPDATE
  namespaceSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: NotIn # you probably don't want the policy to impact this namespace and other ones
        values: [kube-system]
  settings:
    mandatory_labels:
      - owner
```

I didn't try out the policy defintion, but it should work and point you in the right direction.

Let me know if you have other issues

**Comment by saiben10** [comment]
I have applied the same but stil namespace is creating without providing owner label.
getting like this whenn i try to describe the policy

Name:         namespace-must-have-owner-label
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  policies.kubewarden.io/v1
Kind:         ClusterAdmissionPolicy
Metadata:
  Creation Timestamp:  2024-10-24T09:05:01Z
  Finalizers:
    kubewarden.io/finalizer
  Generation:        1
  Resource Version:  941797495
  UID:               2508b8ac-7852-426e-9402-434710a0b1e2
Spec:
  Background Audit:  true
  Mode:              protect
  Module:            ghcr.io/kubewarden/policies/safe-labels:v0.1.14
  Mutating:          false
  Namespace Selector:
    Match Expressions:
      Key:       kubernetes.io/metadata.name
      Operator:  NotIn
      Values:
        kube-system
  Policy Server:  default
  Rules:
    API Groups:
      
    API Versions:
      v1
    Operations:
      CREATE
      UPDATE
    Resources:
      namespaces
  Settings:
    mandatory_labels:
      owner
  Timeout Seconds:  10
Status:
  Conditions:
    Last Transition Time:  2024-10-24T09:05:01Z
    Message:               The policy webhook has not been created
    Reason:                PolicyActive
    Status:                False
    Type:                  PolicyActive
  Policy Status:           scheduled
Events:                    <none>


what  might be the issue the controller pods are running fine

**Comment by saiben10** [comment]
can you please clarify on this @flavio

**Comment by saiben10** [comment]
Hey @flavio even though i applied the above policy still not working
when i describe the above one it is showing policy webhook has not created. Any specific reason.

I followed the below steps
1) Installed kubewarden crds and controller
2) Applying the above policies.


Am i doing anything wrong.

**Comment by saiben10** [comment]
Could you please clarify on this as we are waiting for the response@flavio

**Comment by flavio** [comment]
Can you clarify if you're trying to block the creation of Namespaces without that label set OR if you want to have the Namespace mutated so that the owner label is set to a specific value?

I tested the policy for the 1st scenario (prevent the creation of Namespace objects that do not have the label set)

**Comment by saiben10** [comment]
yes @flavio prevention of namespace if we wont specify owner label but for it didn't worked

**Comment by flavio** [comment]
What is the output of:

```console
kubectl get clusteradmissionpolicies.policies.kubewarden.io
```

Also, please take a look at the logs of the Policy Server where the policy is schedule (it should be the `default` one):

```
kubectl get logs -n kubewarden <pod running the default policy server>
```

You can also increase its verbosity by editing the associated `PolicyServer` CR, you can set the `KUBEWARDEN_LOG_LEVEL` environment variable to be `debug`. It should look similar to this snippet:

```
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: default
spec:
  env:
  - name: KUBEWARDEN_LOG_LEVEL
    value: debug
  image: ghcr.io/kubewarden/policy-server:v1.17.0
  replicas: 1
  serviceAccountName: policy-server
```
