### ISSUE TITLE
[SURE-9642] kubewarden automatic cert rotation while deploying with argoCD

### ISSUE THREAD

**Issue by kkaempf** [kubewarden/kubewarden-controller#980]
### Issue description:
After deploying kubewarden with argocd, kubewarden controller logs shows cert-rotation happens everyday which causes issues in policy server.
~~~
{"level":"info","ts":"2025-01-17T08:41:25Z","logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":"2025-01-17T08:41:25Z","logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":"2025-01-17T08:41:25Z","logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":"2025-01-17T08:41:25Z","logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":"2025-01-17T08:46:02Z","logger":"cert-recociler","msg":"Certificate verification failed, rotating the certificate","dnsName":"policy-server-default.kubewarden-system.svc","verification error":"the certificate is invalid: x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"kubewarden-controller-ca\")"}
{"level":"info","ts":"2025-01-17T08:46:02Z","logger":"cert-recociler","msg":"Certificate rotated successfully","dnsName":"policy-server-default.kubewarden-system.svc"}
~~~

### Troubleshooting steps:

I was able to reproduce it locally
1) Installed kube-warden at 2025-01-15T08:46:02Z (UTC)
2) Next day, got the above logs that tis cert is updated at 2025-01-16T08:41:07Z
3) Next day again, tls updated at 2025-01-17T08:41:25Z
4) ArgoCD detected a change(since self heal is enabled) and auto synced around 2025-01-17T08:41:00Z, thought that argocd initiated this
6) Last cert update shows that its certificate created 1 second earlier than argocd sync

So its not so clear who initiated the change,

Due to this, policy server at customer side having issues and following is the log from api server

 kube-api log :
~~~
W1129 15:49:19.047350 1 dispatcher.go:225] Failed calling webhook, failing closed clusterwide-fs-group.kubewarden.admission: failed calling webhook "clusterwide-fs-group.kubewarden.admission": failed to call webhook: Post "https://policy-server-default.kubewarden.svc:8443/validate/clusterwide-fs-group?timeout=30s": tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "kubewarden-controller-ca")
~~~

Noticed during troubleshooting call that, policy server is serving old certificate, but the CA certificate in the kubewarden webhook is newly created one, which caused the issue. Got inside the container and examined the tls.crt mounted inside policy server pod , that is too newly created tls.crt. As a workearound, we recreated the one of the policy server pod, which resolved the issue. I can see second replica still serving old certificate. So first question, why policy server cant detect the cert change and reload the certificate and serve the same? Moreover, here is no reason to auto rotation of certification when CA has 10 year validity and server certificate has 1 year validity.

We kept argoCD sync off, issue never happened again. But customer want to enable the sync.

Looks like some changes happens at kubewarden end causes argoCD to auto sync. Not so clear whether some cert changes causes argocd to behave like that.

Strangely, newly created certificate timestamps shows, it created 1 second earlier than argoCD sync
~~~
Jan 17 08:40:59 2025 
~~~

### Repro steps:

Simply deploy the kubewarden using argocd
Wait for a day
Around exact time next day(5 min early), kube-warden controller logs show updated current TLS certificate.

### Workaround:
Is a workaround available and implemented? yes/no
1) Restart policy server pod manually to fix it everyday, not desired.
2) Disable auto sync in ArgoCD, not desired

### Actual behavior:
Cert rotation happens in kubewarden when auto sync is enabled in ArgoCD and policy server is failing with cert verification error

### Expected behavior:
Cert rotation shouldnt happen in kubewarden when auto sync is enabled in ArgoCD and even if it happens, policy server should auto recover and serve the new certificates

### Files, logs, traces:

Rotated certificates:
1)
~~~
Issuer: CN = kubewarden-controller-ca
Validity
Not Before: Jan 17 08:40:59 2025 GMT
Not After : Jan 17 08:40:59 2026 GMT
Subject: CN = kubewarden-controller-webhook-service.kubewarden-system.svc
~~~

2)
~~~
Issuer: CN = kubewarden-controller-ca
Validity
Not Before: Jan 17 08:40:59 2025 GMT
Not After : Jan 15 08:40:59 2035 GMT
Subject: CN = kubewarden-controller-ca
~~~

3) Seems policy server certificate rotated after 6min after CA and webhook

~~~
Issuer: CN = kubewarden-controller-ca
Validity
Not Before: Jan 17 08:46:02 2025 GMT
Not After : Jan 17 08:46:02 2026 GMT
Subject: CN = policy-server-default.kubewarden-system.svc
~~~

4) Accessing policy server in problematic scenario: shows 1 day old certificate, actually policy server created and started 2 days ago.

~~~
curl -vk https://policy-server-default.kubewarden-system.svc:8443/

Trying 10.43.222.158:8443...
Connected to policy-server-default.kubewarden-system.svc (10.43.222.158) port 8443 (#0)
ALPN: offers h2,http/1.1
TLSv1.3 (OUT), TLS handshake, Client hello (1):
TLSv1.3 (IN), TLS handshake, Server hello (2):
TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
TLSv1.3 (IN), TLS handshake, Certificate (11):
TLSv1.3 (IN), TLS handshake, CERT verify (15):
TLSv1.3 (IN), TLS handshake, Finished (20):
TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
TLSv1.3 (OUT), TLS handshake, Finished (20):
SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
ALPN: server accepted h2
Server certificate:
subject: CN=policy-server-default.kubewarden-system.svc
start date: Jan 16 08:46:02 2025 GMT
expire date: Jan 16 08:46:02 2026 GMT
issuer: CN=kubewarden-controller-ca
SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
~~~

### Additional notes:
Any specific recommendation to disable selfheal when using gitops?

**Comment by jvanz** [comment]
Ok, let me share some findings...

Thanks for the detailed information, I was able to simulate the issue. I can see the cert-controller inside the Kubewarden controller rotating the policy server certificate. However,  this should not happen unless something change the CA certificate. As I do not want to wait for the daily ArgoCD sync I've discovered that I can kind of simulate the behavior doing a hard refresh. Also, to speed up things, I've changed the cert-controller to run every 3 minutes (instead of 12 hours) and added some debug logs. Furthermore, I've decided to test only the Kubewarden controller with no policy server running. Just to isolate things. Because if the CA certificate change I do not need the policy server to see that.

I can see that after I trigger an hard reset, the CA secret, webhook secret , validatingwebhookconfiguration and mutatingwebhookconfiguration has been updated. Even if I did not change anything it. In other words, ti should not deviated from the desired state. I've also tried to deploy a policy after the hard refresh and it works. Which means that webhooks to validate our CRDs, the ones updated during the hard refresh,  are working fine. So, I believe that the hard refresh is recreating the secrets and the webhooks. What may explain that is that `kubewarden-controller` Helm chart generates the first certificates used by this resources in the template. Which may explain why ArgoCD is recreating it every time. It looks like that when the chart is installed by ArgoCD it cannot find the old secret in the cluster. Therefore, it will recreated it. To validate this I've change a little bit the helm chart to add another field if an UUID generated in the template as well and added to the secret data. This is the steps that I follow using this modified helm chart:

1. Install kubewarden-crds and kubewarden-controller using ArgoCD.
2. collect secrets and webhooks for comparison
3. Trigger a hard refresh
4. collect secret and webhooks configuration and compare with the ones collected in step 2

This is the diff for the kubewarden-ca secret:

 
```console
diff kubewarden-ca-2025-01-24T09:34:38-03:00.json kubewarden-ca-2025-01-24T09:37:07-03:00.json
4,6c4,6
<         "ca.crt": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwakNDQVV1Z0F3SUJBZ0lRR2FTK2lvS2ZBMWlnbkJnSGdCZjA3VEFLQmdncWhrak9QUVFEQWpBak1TRXcKSHdZRFZRUURFeGhyZFdKbGQyRnlaR1Z1TFdOdmJuUnliMnhzWlhJdFkyRXdIaGNOTWpVd01USTBNVEl6TXpVegpXaGNOTXpVd01USXlNVEl6TXpVeldqQWpNU0V3SHdZRFZRUURFeGhyZFdKbGQyRnlaR1Z1TFdOdmJuUnliMnhzClpYSXRZMkV3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVM2TlR4OU1yLzhTMVhmRTFoRGVMRmoKQ0w2NlNhSk1FRGlkd1hoR3A2RDFDRXAyM0ZFZit2ZDZBMmM2UDAzZmZOYTBNYk1rSEd0NUJZbnMwQ05mTkwzZgpvMkV3WHpBT0JnTlZIUThCQWY4RUJBTUNBcVF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGCkJ3TUNNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGTmNrMzhOV1U0V3VPSG9Ud1ZjTGR4eFoKNllNTE1Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQ0lRREt5b2VRRUkwcXo1QWdiUHEyYXJWV0wwdWdVcWVFZ0MrZApERFdUbEE2bm13SWhBUFg1dERMUjY5VkE0cXQyb0dwZDQ3Z2NpdlV5N1IzY2J4bis5bzVHMkxEYgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==",
<         "ca.key": "LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU9QNXpzenFVZTkrUGhHOXBobFpjdWwyc1FSclJGVE5BM0crL1hRaE85NXNvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFdWpVOGZUSy8vRXRWM3hOWVEzaXhZd2krdWttaVRCQTRuY0Y0UnFlZzlRaEtkdHhSSC9yMwplZ05uT2o5TjMzeld0REd6SkJ4cmVRV0o3TkFqWHpTOTN3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=",
<         "date": "ZDRjYzdhYTktYzg1OS00NjAwLWE5MzItODM4NjFjMzZjZmQz"
—
>         "ca.crt": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwVENDQVV1Z0F3SUJBZ0lRSUx0cGVyVUxSd25DcDk3S0ExSjlTakFLQmdncWhrak9QUVFEQWpBak1TRXcKSHdZRFZRUURFeGhyZFdKbGQyRnlaR1Z1TFdOdmJuUnliMnhzWlhJdFkyRXdIaGNOTWpVd01USTBNVEl6TmpNMApXaGNOTXpVd01USXlNVEl6TmpNMFdqQWpNU0V3SHdZRFZRUURFeGhyZFdKbGQyRnlaR1Z1TFdOdmJuUnliMnhzClpYSXRZMkV3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFmT3FwdmJpYjRqRGxLT2M3ZzUwbmEKS2NaeFdibCsrT0syeWF5Uyt0S1R1RGZ6RW9RN0hoZ1c5cFNJcDFwK1hiaWtZRU9hUnN1dXNLTXBnbHNSL3dHTwpvMkV3WHpBT0JnTlZIUThCQWY4RUJBTUNBcVF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGCkJ3TUNNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGUG9JNXlQMGJWcEVheUVmMU9ZTVJvWS8KRlhzUE1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lBYUNCc3pHdWxCUlIvdHRWYjRZMWtYVXpyTkFhakxpSFFXTQpFQSsvNHhwWkFpRUFyWVduVmplMDhEdVdubFJOR2kzMGxHc1dEU1A0Ni9CcFNIZGNQeUhqR01rPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==",
>         "ca.key": "LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSURqeG9ySjcraEpJZTR0U1hOS3R4TXVIa1dZMCtkVTduTnNwRm1kZm0zYXZvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFSHpxcWIyNG0rSXc1U2puTzRPZEoyaW5HY1ZtNWZ2aml0c21za3ZyU2s3ZzM4eEtFT3g0WQpGdmFVaUtkYWZsMjRwR0JEbWtiTHJyQ2pLWUpiRWY4QmpnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=",
>         "date": "NzNkMjkzNTYtMGFjZS00NjE3LWIxNmUtODAwYmY3NDc0OGRk"
11c11
<             "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"data\":
{\"ca.crt\":\"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwakNDQVV1Z0F3SUJBZ0lRR2FTK2lvS2ZBMWlnbkJnSGdCZjA3VEFLQmdncWhrak9QUVFEQWpBak1TRXcKSHdZRFZRUURFeGhyZFdKbGQyRnlaR1Z1TFdOdmJuUnliMnhzWlhJdFkyRXdIaGNOTWpVd01USTBNVEl6TXpVegpXaGNOTXpVd01USXlNVEl6TXpVeldqQWpNU0V3SHdZRFZRUURFeGhyZFdKbGQyRnlaR1Z1TFdOdmJuUnliMnhzClpYSXRZMkV3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVM2TlR4OU1yLzhTMVhmRTFoRGVMRmoKQ0w2NlNhSk1FRGlkd1hoR3A2RDFDRXAyM0ZFZit2ZDZBMmM2UDAzZmZOYTBNYk1rSEd0NUJZbnMwQ05mTkwzZgpvMkV3WHpBT0JnTlZIUThCQWY4RUJBTUNBcVF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGCkJ3TUNNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGTmNrMzhOV1U0V3VPSG9Ud1ZjTGR4eFoKNllNTE1Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQ0lRREt5b2VRRUkwcXo1QWdiUHEyYXJWV0wwdWdVcWVFZ0MrZApERFdUbEE2bm13SWhBUFg1dERMUjY5VkE0cXQyb0dwZDQ3Z2NpdlV5N1IzY2J4bis5bzVHMkxEYgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==\",\"ca.key\":\"LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU9QNXpzenFVZTkrUGhHOXBobFpjdWwyc1FSclJGVE5BM0crL1hRaE85NXNvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFdWpVOGZUSy8vRXRWM3hOWVEzaXhZd2krdWttaVRCQTRuY0Y0UnFlZzlRaEtkdHhSSC9yMwplZ05uT2o5TjMzeld0REd6SkJ4cmVRV0o3TkFqWHpTOTN3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=\",\"date\":\"ZDRjYzdhYTktYzg1OS00NjAwLWE5MzItODM4NjFjMzZjZmQz\"}
,\"kind\":\"Secret\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/component\":\"controller\",\"app.kubernetes.io/instance\":\"kubewarden-controller\",\"app.kubernetes.io/managed-by\":\"Helm\",\"app.kubernetes.io/name\":\"kubewarden-controller\",\"app.kubernetes.io/part-of\":\"kubewarden\",\"app.kubernetes.io/version\":\"v2.0.0-rc1\",\"helm.sh/chart\":\"kubewarden-controller-5.0.0-rc4\"},\"name\":\"kubewarden-ca\",\"namespace\":\"kubewarden-system\"}}\n"
—
>             "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"data\":
{\"ca.crt\":\"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwVENDQVV1Z0F3SUJBZ0lRSUx0cGVyVUxSd25DcDk3S0ExSjlTakFLQmdncWhrak9QUVFEQWpBak1TRXcKSHdZRFZRUURFeGhyZFdKbGQyRnlaR1Z1TFdOdmJuUnliMnhzWlhJdFkyRXdIaGNOTWpVd01USTBNVEl6TmpNMApXaGNOTXpVd01USXlNVEl6TmpNMFdqQWpNU0V3SHdZRFZRUURFeGhyZFdKbGQyRnlaR1Z1TFdOdmJuUnliMnhzClpYSXRZMkV3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFmT3FwdmJpYjRqRGxLT2M3ZzUwbmEKS2NaeFdibCsrT0syeWF5Uyt0S1R1RGZ6RW9RN0hoZ1c5cFNJcDFwK1hiaWtZRU9hUnN1dXNLTXBnbHNSL3dHTwpvMkV3WHpBT0JnTlZIUThCQWY4RUJBTUNBcVF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGCkJ3TUNNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGUG9JNXlQMGJWcEVheUVmMU9ZTVJvWS8KRlhzUE1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lBYUNCc3pHdWxCUlIvdHRWYjRZMWtYVXpyTkFhakxpSFFXTQpFQSsvNHhwWkFpRUFyWVduVmplMDhEdVdubFJOR2kzMGxHc1dEU1A0Ni9CcFNIZGNQeUhqR01rPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==\",\"ca.key\":\"LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSURqeG9ySjcraEpJZTR0U1hOS3R4TXVIa1dZMCtkVTduTnNwRm1kZm0zYXZvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFSHpxcWIyNG0rSXc1U2puTzRPZEoyaW5HY1ZtNWZ2aml0c21za3ZyU2s3ZzM4eEtFT3g0WQpGdmFVaUtkYWZsMjRwR0JEbWtiTHJyQ2pLWUpiRWY4QmpnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=\",\"date\":\"NzNkMjkzNTYtMGFjZS00NjE3LWIxNmUtODAwYmY3NDc0OGRk\"}
,\"kind\":\"Secret\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/component\":\"controller\",\"app.kubernetes.io/instance\":\"kubewarden-controller\",\"app.kubernetes.io/managed-by\":\"Helm\",\"app.kubernetes.io/name\":\"kubewarden-controller\",\"app.kubernetes.io/part-of\":\"kubewarden\",\"app.kubernetes.io/version\":\"v2.0.0-rc1\",\"helm.sh/chart\":\"kubewarden-controller-5.0.0-rc4\"},\"name\":\"kubewarden-ca\",\"namespace\":\"kubewarden-system\"}}\n"
25c25
<         "resourceVersion": "1944",
—
>         "resourceVersion": "2263",
```
 

As you can see, the secret has been changed. We can see that by the change in the `resourceVersion` and the `date` ( the field with the UUID that I've added) field in the `data`. If the CA certificate change, that will explain why the policy server certificates will be rotated later on. 

Now,  let me think a proper solution

**Comment by jvanz** [comment]
I believe I can describe the entire scenario of the issue. My previous comment is still valid: ArgoCD is recreating the certificates from time to time, but I was unsure why exactly. I spent a day investigating how ArgoCD works and conducting tests. To do this, I recreated a cluster with ArgoCD and installed Kubewarden as an ArgoCD application with self-healing disabled.

The first thing I noticed was that right after the installation, ArgoCD marked the certificate secrets and webhooks configuration as out of sync, which is odd because the resources were just installed. This suggests that ArgoCD was rendering the Helm templates at least twice: once for the initial installation and a second time immediately afterward. If we sync the application after that, it continues to show as synced until I perform a hard refresh or wait for a day, as described by the users. This is also odd because I made no changes to the resources. Therefore, the app state is stored for a day that causes ArgoCD to consider the application state synced. It's not just the sync loop, as the loop that verifies the application state runs, as far as I can remember from the documentation, every 3 minutes.

While reading the ArgoCD documentation, I noticed that the cache used to store the application state has an expiration timeout of 24 hours. This explains why users want to wait one day to see the issue and why I can simulate the issue by performing a hard refresh. A hard refresh forces ArgoCD to ignore the cache and render the application resources from the Helm chart again. Thus, the certificates are generated again, marking the app as out of sync.

To summarize, the problem timeline is as follows:
1. User installs Kubewarden applications.\
2. For some reason, ArgoCD renders the templates again and stores them in the cache. Furthermore, since self-healing is enabled, the sync loop applies the changes in the cluster.
3. After 24 hours, the resources in the cache expire, and the controller renders the templates from the Helm chart again and stores them in the cache.
4. The self-healing loop detects the changes and applies them.
5. During this process, the cert-controller in the Kubewarden controller notices the change in the certificate and performs the rotation.

These steps can be validated when the application is installed with self-healing disabled. The ArgoCD history shows that all the resources are "created," and after a manual sync, the secrets and webhook configuration show as "configured." However, when the application is installed with self-healing enabled, ArgoCD shows that all the resources are "created," but the secrets and the webhook configuration are "configured," indicating that they were updated after creation.

To fix this, we can instruct ArgoCD to ignore the data field in the secrets and the caBundle field in the webhook configuration. To validate this fix, I created a cluster with ArgoCD and set a cache timeout of 5 minutes, with the Kubewarden cert-controller running every 3 minutes. The cluster ran over the weekend, and no sync was performed during this period.

Here is my argocd-cmd-params-cm ConfigMap to change the cache expiration time:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  controller.app.state.cache.expiration: 5m
  controller.default.cache.expiration: 5m
  reposerver.default.cache.expiration: 5m
  reposerver.repo.cache.expiration: 5m
  server.app.state.cache.expiration: 5m
  server.default.cache.expiration: 5m
```

Here is my ArgoCD application definition:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubewarden-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.kubewarden.io
    chart: kubewarden-crds
    targetRevision: 1.13.0-rc1
  destination:
    server: https://kubernetes.default.svc
    namespace: kubewarden-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubewarden-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.kubewarden.io
    chart: kubewarden-controller
    targetRevision: 4.1.0-rc1
    helm:
      parameters:
        - name: image.repository
          value: ghcr.io/jvanz/kubewarden-controller
        - name: image.tag
          value: issue1026v3
  destination:
    server: https://kubernetes.default.svc
    namespace: kubewarden-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:     # Sync options which modifies sync behavior
      - RespectIgnoreDifferences=true # When syncing changes, respect fields ignored by the ignoreDifferences configuration
  ignoreDifferences:
  - group: ""
    kind: "Secret"
    name: kubewarden-ca
    namespace: kubewarden-system
    jsonPointers:
      - /data
  - group: ""
    kind: "Secret"
    name: kubewarden-webhook-server-cert
    namespace: kubewarden-system
    jsonPointers:
      - /data
  - group: "admissionregistration.k8s.io"
    kind: "MutatingWebhookConfiguration"
    jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
  - group: "admissionregistration.k8s.io"
    kind: "ValidatingWebhookConfiguration"
    jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubewarden-defaults
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.kubewarden.io
    chart: kubewarden-defaults
    targetRevision: 2.8.0-rc1
    helm:
      parameters:
        - name: recommendedPolicies.enabled
          value: "True"
  destination:
    server: https://kubernetes.default.svc
    namespace: kubewarden-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

> [!NOTE]  
> I'm using the latest version of the Helm chart because I'm working with a modified version of the Kubewarden controller. However, this should work with any version of the controller that generates the certificates in the Helm charts

To fix the issue, the user can configure the application to ignore the `data` field in the secrets and the `caBundle` in the webhook configuration (the `ignoreDifferences` configuration in the `kubewarden-controller` application). This will prevent the cert-controller from performing unnecessary rotations and causing issues. I'll also update our documentation with this information. Furthermore, regarding the issue of the policy server not loading the certificates, I'll try to simulate the problem and find a solution if necessary. ;)
